const githubResult = ''' {
  "total_count": 41,
  "incomplete_results": false,
  "items": [
    {
      "login": "mcfrank",
      "id": 1158807,
      "node_id": "MDQ6VXNlcjExNTg4MDc=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1158807?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mcfrank",
      "html_url": "https://github.com/mcfrank",
      "followers_url": "https://api.github.com/users/mcfrank/followers",
      "following_url": "https://api.github.com/users/mcfrank/following{/other_user}",
      "gists_url": "https://api.github.com/users/mcfrank/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mcfrank/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mcfrank/subscriptions",
      "organizations_url": "https://api.github.com/users/mcfrank/orgs",
      "repos_url": "https://api.github.com/users/mcfrank/repos",
      "events_url": "https://api.github.com/users/mcfrank/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mcfrank/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "maickom88",
      "id": 48966499,
      "node_id": "MDQ6VXNlcjQ4OTY2NDk5",
      "avatar_url": "https://avatars3.githubusercontent.com/u/48966499?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/maickom88",
      "html_url": "https://github.com/maickom88",
      "followers_url": "https://api.github.com/users/maickom88/followers",
      "following_url": "https://api.github.com/users/maickom88/following{/other_user}",
      "gists_url": "https://api.github.com/users/maickom88/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/maickom88/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/maickom88/subscriptions",
      "organizations_url": "https://api.github.com/users/maickom88/orgs",
      "repos_url": "https://api.github.com/users/maickom88/repos",
      "events_url": "https://api.github.com/users/maickom88/events{/privacy}",
      "received_events_url": "https://api.github.com/users/maickom88/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "frankenmichl",
      "id": 5319409,
      "node_id": "MDQ6VXNlcjUzMTk0MDk=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/5319409?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/frankenmichl",
      "html_url": "https://github.com/frankenmichl",
      "followers_url": "https://api.github.com/users/frankenmichl/followers",
      "following_url": "https://api.github.com/users/frankenmichl/following{/other_user}",
      "gists_url": "https://api.github.com/users/frankenmichl/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/frankenmichl/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/frankenmichl/subscriptions",
      "organizations_url": "https://api.github.com/users/frankenmichl/orgs",
      "repos_url": "https://api.github.com/users/frankenmichl/repos",
      "events_url": "https://api.github.com/users/frankenmichl/events{/privacy}",
      "received_events_url": "https://api.github.com/users/frankenmichl/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "msfrank",
      "id": 183977,
      "node_id": "MDQ6VXNlcjE4Mzk3Nw==",
      "avatar_url": "https://avatars1.githubusercontent.com/u/183977?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/msfrank",
      "html_url": "https://github.com/msfrank",
      "followers_url": "https://api.github.com/users/msfrank/followers",
      "following_url": "https://api.github.com/users/msfrank/following{/other_user}",
      "gists_url": "https://api.github.com/users/msfrank/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/msfrank/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/msfrank/subscriptions",
      "organizations_url": "https://api.github.com/users/msfrank/orgs",
      "repos_url": "https://api.github.com/users/msfrank/repos",
      "events_url": "https://api.github.com/users/msfrank/events{/privacy}",
      "received_events_url": "https://api.github.com/users/msfrank/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mud5150",
      "id": 7492554,
      "node_id": "MDQ6VXNlcjc0OTI1NTQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/7492554?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mud5150",
      "html_url": "https://github.com/mud5150",
      "followers_url": "https://api.github.com/users/mud5150/followers",
      "following_url": "https://api.github.com/users/mud5150/following{/other_user}",
      "gists_url": "https://api.github.com/users/mud5150/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mud5150/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mud5150/subscriptions",
      "organizations_url": "https://api.github.com/users/mud5150/orgs",
      "repos_url": "https://api.github.com/users/mud5150/repos",
      "events_url": "https://api.github.com/users/mud5150/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mud5150/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "frankl1",
      "id": 23366578,
      "node_id": "MDQ6VXNlcjIzMzY2NTc4",
      "avatar_url": "https://avatars2.githubusercontent.com/u/23366578?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/frankl1",
      "html_url": "https://github.com/frankl1",
      "followers_url": "https://api.github.com/users/frankl1/followers",
      "following_url": "https://api.github.com/users/frankl1/following{/other_user}",
      "gists_url": "https://api.github.com/users/frankl1/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/frankl1/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/frankl1/subscriptions",
      "organizations_url": "https://api.github.com/users/frankl1/orgs",
      "repos_url": "https://api.github.com/users/frankl1/repos",
      "events_url": "https://api.github.com/users/frankl1/events{/privacy}",
      "received_events_url": "https://api.github.com/users/frankl1/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Michael-Frank",
      "id": 7025081,
      "node_id": "MDQ6VXNlcjcwMjUwODE=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/7025081?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Michael-Frank",
      "html_url": "https://github.com/Michael-Frank",
      "followers_url": "https://api.github.com/users/Michael-Frank/followers",
      "following_url": "https://api.github.com/users/Michael-Frank/following{/other_user}",
      "gists_url": "https://api.github.com/users/Michael-Frank/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Michael-Frank/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Michael-Frank/subscriptions",
      "organizations_url": "https://api.github.com/users/Michael-Frank/orgs",
      "repos_url": "https://api.github.com/users/Michael-Frank/repos",
      "events_url": "https://api.github.com/users/Michael-Frank/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Michael-Frank/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "fmscode",
      "id": 1703189,
      "node_id": "MDQ6VXNlcjE3MDMxODk=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/1703189?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fmscode",
      "html_url": "https://github.com/fmscode",
      "followers_url": "https://api.github.com/users/fmscode/followers",
      "following_url": "https://api.github.com/users/fmscode/following{/other_user}",
      "gists_url": "https://api.github.com/users/fmscode/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fmscode/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fmscode/subscriptions",
      "organizations_url": "https://api.github.com/users/fmscode/orgs",
      "repos_url": "https://api.github.com/users/fmscode/repos",
      "events_url": "https://api.github.com/users/fmscode/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fmscode/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MichaelFrankOfficial",
      "id": 32846440,
      "node_id": "MDQ6VXNlcjMyODQ2NDQw",
      "avatar_url": "https://avatars3.githubusercontent.com/u/32846440?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MichaelFrankOfficial",
      "html_url": "https://github.com/MichaelFrankOfficial",
      "followers_url": "https://api.github.com/users/MichaelFrankOfficial/followers",
      "following_url": "https://api.github.com/users/MichaelFrankOfficial/following{/other_user}",
      "gists_url": "https://api.github.com/users/MichaelFrankOfficial/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MichaelFrankOfficial/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MichaelFrankOfficial/subscriptions",
      "organizations_url": "https://api.github.com/users/MichaelFrankOfficial/orgs",
      "repos_url": "https://api.github.com/users/MichaelFrankOfficial/repos",
      "events_url": "https://api.github.com/users/MichaelFrankOfficial/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MichaelFrankOfficial/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mikepfrank",
      "id": 3827484,
      "node_id": "MDQ6VXNlcjM4Mjc0ODQ=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/3827484?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikepfrank",
      "html_url": "https://github.com/mikepfrank",
      "followers_url": "https://api.github.com/users/mikepfrank/followers",
      "following_url": "https://api.github.com/users/mikepfrank/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikepfrank/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikepfrank/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikepfrank/subscriptions",
      "organizations_url": "https://api.github.com/users/mikepfrank/orgs",
      "repos_url": "https://api.github.com/users/mikepfrank/repos",
      "events_url": "https://api.github.com/users/mikepfrank/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikepfrank/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "michafrank",
      "id": 22541135,
      "node_id": "MDQ6VXNlcjIyNTQxMTM1",
      "avatar_url": "https://avatars2.githubusercontent.com/u/22541135?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michafrank",
      "html_url": "https://github.com/michafrank",
      "followers_url": "https://api.github.com/users/michafrank/followers",
      "following_url": "https://api.github.com/users/michafrank/following{/other_user}",
      "gists_url": "https://api.github.com/users/michafrank/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michafrank/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michafrank/subscriptions",
      "organizations_url": "https://api.github.com/users/michafrank/orgs",
      "repos_url": "https://api.github.com/users/michafrank/repos",
      "events_url": "https://api.github.com/users/michafrank/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michafrank/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ITspirit",
      "id": 2453696,
      "node_id": "MDQ6VXNlcjI0NTM2OTY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/2453696?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ITspirit",
      "html_url": "https://github.com/ITspirit",
      "followers_url": "https://api.github.com/users/ITspirit/followers",
      "following_url": "https://api.github.com/users/ITspirit/following{/other_user}",
      "gists_url": "https://api.github.com/users/ITspirit/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ITspirit/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ITspirit/subscriptions",
      "organizations_url": "https://api.github.com/users/ITspirit/orgs",
      "repos_url": "https://api.github.com/users/ITspirit/repos",
      "events_url": "https://api.github.com/users/ITspirit/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ITspirit/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "michaelsfrank",
      "id": 3179286,
      "node_id": "MDQ6VXNlcjMxNzkyODY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/3179286?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelsfrank",
      "html_url": "https://github.com/michaelsfrank",
      "followers_url": "https://api.github.com/users/michaelsfrank/followers",
      "following_url": "https://api.github.com/users/michaelsfrank/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelsfrank/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelsfrank/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelsfrank/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelsfrank/orgs",
      "repos_url": "https://api.github.com/users/michaelsfrank/repos",
      "events_url": "https://api.github.com/users/michaelsfrank/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelsfrank/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "sneakers-n-servers",
      "id": 30980219,
      "node_id": "MDQ6VXNlcjMwOTgwMjE5",
      "avatar_url": "https://avatars3.githubusercontent.com/u/30980219?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sneakers-n-servers",
      "html_url": "https://github.com/sneakers-n-servers",
      "followers_url": "https://api.github.com/users/sneakers-n-servers/followers",
      "following_url": "https://api.github.com/users/sneakers-n-servers/following{/other_user}",
      "gists_url": "https://api.github.com/users/sneakers-n-servers/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sneakers-n-servers/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sneakers-n-servers/subscriptions",
      "organizations_url": "https://api.github.com/users/sneakers-n-servers/orgs",
      "repos_url": "https://api.github.com/users/sneakers-n-servers/repos",
      "events_url": "https://api.github.com/users/sneakers-n-servers/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sneakers-n-servers/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mfrank01-tgm",
      "id": 25742214,
      "node_id": "MDQ6VXNlcjI1NzQyMjE0",
      "avatar_url": "https://avatars1.githubusercontent.com/u/25742214?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mfrank01-tgm",
      "html_url": "https://github.com/mfrank01-tgm",
      "followers_url": "https://api.github.com/users/mfrank01-tgm/followers",
      "following_url": "https://api.github.com/users/mfrank01-tgm/following{/other_user}",
      "gists_url": "https://api.github.com/users/mfrank01-tgm/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mfrank01-tgm/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mfrank01-tgm/subscriptions",
      "organizations_url": "https://api.github.com/users/mfrank01-tgm/orgs",
      "repos_url": "https://api.github.com/users/mfrank01-tgm/repos",
      "events_url": "https://api.github.com/users/mfrank01-tgm/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mfrank01-tgm/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "frankmj",
      "id": 915860,
      "node_id": "MDQ6VXNlcjkxNTg2MA==",
      "avatar_url": "https://avatars0.githubusercontent.com/u/915860?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/frankmj",
      "html_url": "https://github.com/frankmj",
      "followers_url": "https://api.github.com/users/frankmj/followers",
      "following_url": "https://api.github.com/users/frankmj/following{/other_user}",
      "gists_url": "https://api.github.com/users/frankmj/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/frankmj/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/frankmj/subscriptions",
      "organizations_url": "https://api.github.com/users/frankmj/orgs",
      "repos_url": "https://api.github.com/users/frankmj/repos",
      "events_url": "https://api.github.com/users/frankmj/events{/privacy}",
      "received_events_url": "https://api.github.com/users/frankmj/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mofrank",
      "id": 1245579,
      "node_id": "MDQ6VXNlcjEyNDU1Nzk=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/1245579?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mofrank",
      "html_url": "https://github.com/mofrank",
      "followers_url": "https://api.github.com/users/mofrank/followers",
      "following_url": "https://api.github.com/users/mofrank/following{/other_user}",
      "gists_url": "https://api.github.com/users/mofrank/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mofrank/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mofrank/subscriptions",
      "organizations_url": "https://api.github.com/users/mofrank/orgs",
      "repos_url": "https://api.github.com/users/mofrank/repos",
      "events_url": "https://api.github.com/users/mofrank/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mofrank/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "michaelcooke",
      "id": 12518009,
      "node_id": "MDQ6VXNlcjEyNTE4MDA5",
      "avatar_url": "https://avatars1.githubusercontent.com/u/12518009?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michaelcooke",
      "html_url": "https://github.com/michaelcooke",
      "followers_url": "https://api.github.com/users/michaelcooke/followers",
      "following_url": "https://api.github.com/users/michaelcooke/following{/other_user}",
      "gists_url": "https://api.github.com/users/michaelcooke/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michaelcooke/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michaelcooke/subscriptions",
      "organizations_url": "https://api.github.com/users/michaelcooke/orgs",
      "repos_url": "https://api.github.com/users/michaelcooke/repos",
      "events_url": "https://api.github.com/users/michaelcooke/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michaelcooke/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mmfrank",
      "id": 17054995,
      "node_id": "MDQ6VXNlcjE3MDU0OTk1",
      "avatar_url": "https://avatars2.githubusercontent.com/u/17054995?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mmfrank",
      "html_url": "https://github.com/mmfrank",
      "followers_url": "https://api.github.com/users/mmfrank/followers",
      "following_url": "https://api.github.com/users/mmfrank/following{/other_user}",
      "gists_url": "https://api.github.com/users/mmfrank/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mmfrank/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mmfrank/subscriptions",
      "organizations_url": "https://api.github.com/users/mmfrank/orgs",
      "repos_url": "https://api.github.com/users/mmfrank/repos",
      "events_url": "https://api.github.com/users/mmfrank/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mmfrank/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mikemfrank",
      "id": 3266707,
      "node_id": "MDQ6VXNlcjMyNjY3MDc=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/3266707?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikemfrank",
      "html_url": "https://github.com/mikemfrank",
      "followers_url": "https://api.github.com/users/mikemfrank/followers",
      "following_url": "https://api.github.com/users/mikemfrank/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikemfrank/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikemfrank/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikemfrank/subscriptions",
      "organizations_url": "https://api.github.com/users/mikemfrank/orgs",
      "repos_url": "https://api.github.com/users/mikemfrank/repos",
      "events_url": "https://api.github.com/users/mikemfrank/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikemfrank/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "franksum3109",
      "id": 12734877,
      "node_id": "MDQ6VXNlcjEyNzM0ODc3",
      "avatar_url": "https://avatars3.githubusercontent.com/u/12734877?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/franksum3109",
      "html_url": "https://github.com/franksum3109",
      "followers_url": "https://api.github.com/users/franksum3109/followers",
      "following_url": "https://api.github.com/users/franksum3109/following{/other_user}",
      "gists_url": "https://api.github.com/users/franksum3109/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/franksum3109/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/franksum3109/subscriptions",
      "organizations_url": "https://api.github.com/users/franksum3109/orgs",
      "repos_url": "https://api.github.com/users/franksum3109/repos",
      "events_url": "https://api.github.com/users/franksum3109/events{/privacy}",
      "received_events_url": "https://api.github.com/users/franksum3109/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "fbinthesfv",
      "id": 43356810,
      "node_id": "MDQ6VXNlcjQzMzU2ODEw",
      "avatar_url": "https://avatars3.githubusercontent.com/u/43356810?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/fbinthesfv",
      "html_url": "https://github.com/fbinthesfv",
      "followers_url": "https://api.github.com/users/fbinthesfv/followers",
      "following_url": "https://api.github.com/users/fbinthesfv/following{/other_user}",
      "gists_url": "https://api.github.com/users/fbinthesfv/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/fbinthesfv/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/fbinthesfv/subscriptions",
      "organizations_url": "https://api.github.com/users/fbinthesfv/orgs",
      "repos_url": "https://api.github.com/users/fbinthesfv/repos",
      "events_url": "https://api.github.com/users/fbinthesfv/events{/privacy}",
      "received_events_url": "https://api.github.com/users/fbinthesfv/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "kiwibayer",
      "id": 25971956,
      "node_id": "MDQ6VXNlcjI1OTcxOTU2",
      "avatar_url": "https://avatars0.githubusercontent.com/u/25971956?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/kiwibayer",
      "html_url": "https://github.com/kiwibayer",
      "followers_url": "https://api.github.com/users/kiwibayer/followers",
      "following_url": "https://api.github.com/users/kiwibayer/following{/other_user}",
      "gists_url": "https://api.github.com/users/kiwibayer/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/kiwibayer/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/kiwibayer/subscriptions",
      "organizations_url": "https://api.github.com/users/kiwibayer/orgs",
      "repos_url": "https://api.github.com/users/kiwibayer/repos",
      "events_url": "https://api.github.com/users/kiwibayer/events{/privacy}",
      "received_events_url": "https://api.github.com/users/kiwibayer/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "m210658",
      "id": 6668912,
      "node_id": "MDQ6VXNlcjY2Njg5MTI=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/6668912?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/m210658",
      "html_url": "https://github.com/m210658",
      "followers_url": "https://api.github.com/users/m210658/followers",
      "following_url": "https://api.github.com/users/m210658/following{/other_user}",
      "gists_url": "https://api.github.com/users/m210658/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/m210658/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/m210658/subscriptions",
      "organizations_url": "https://api.github.com/users/m210658/orgs",
      "repos_url": "https://api.github.com/users/m210658/repos",
      "events_url": "https://api.github.com/users/m210658/events{/privacy}",
      "received_events_url": "https://api.github.com/users/m210658/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "mikes4bikes",
      "id": 42330331,
      "node_id": "MDQ6VXNlcjQyMzMwMzMx",
      "avatar_url": "https://avatars3.githubusercontent.com/u/42330331?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mikes4bikes",
      "html_url": "https://github.com/mikes4bikes",
      "followers_url": "https://api.github.com/users/mikes4bikes/followers",
      "following_url": "https://api.github.com/users/mikes4bikes/following{/other_user}",
      "gists_url": "https://api.github.com/users/mikes4bikes/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mikes4bikes/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mikes4bikes/subscriptions",
      "organizations_url": "https://api.github.com/users/mikes4bikes/orgs",
      "repos_url": "https://api.github.com/users/mikes4bikes/repos",
      "events_url": "https://api.github.com/users/mikes4bikes/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mikes4bikes/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "MFrank84",
      "id": 10529424,
      "node_id": "MDQ6VXNlcjEwNTI5NDI0",
      "avatar_url": "https://avatars2.githubusercontent.com/u/10529424?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/MFrank84",
      "html_url": "https://github.com/MFrank84",
      "followers_url": "https://api.github.com/users/MFrank84/followers",
      "following_url": "https://api.github.com/users/MFrank84/following{/other_user}",
      "gists_url": "https://api.github.com/users/MFrank84/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/MFrank84/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/MFrank84/subscriptions",
      "organizations_url": "https://api.github.com/users/MFrank84/orgs",
      "repos_url": "https://api.github.com/users/MFrank84/repos",
      "events_url": "https://api.github.com/users/MFrank84/events{/privacy}",
      "received_events_url": "https://api.github.com/users/MFrank84/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "michael-frank-vector",
      "id": 58934843,
      "node_id": "MDQ6VXNlcjU4OTM0ODQz",
      "avatar_url": "https://avatars1.githubusercontent.com/u/58934843?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michael-frank-vector",
      "html_url": "https://github.com/michael-frank-vector",
      "followers_url": "https://api.github.com/users/michael-frank-vector/followers",
      "following_url": "https://api.github.com/users/michael-frank-vector/following{/other_user}",
      "gists_url": "https://api.github.com/users/michael-frank-vector/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michael-frank-vector/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michael-frank-vector/subscriptions",
      "organizations_url": "https://api.github.com/users/michael-frank-vector/orgs",
      "repos_url": "https://api.github.com/users/michael-frank-vector/repos",
      "events_url": "https://api.github.com/users/michael-frank-vector/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michael-frank-vector/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "michael-frank1989",
      "id": 2526650,
      "node_id": "MDQ6VXNlcjI1MjY2NTA=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/2526650?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/michael-frank1989",
      "html_url": "https://github.com/michael-frank1989",
      "followers_url": "https://api.github.com/users/michael-frank1989/followers",
      "following_url": "https://api.github.com/users/michael-frank1989/following{/other_user}",
      "gists_url": "https://api.github.com/users/michael-frank1989/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/michael-frank1989/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/michael-frank1989/subscriptions",
      "organizations_url": "https://api.github.com/users/michael-frank1989/orgs",
      "repos_url": "https://api.github.com/users/michael-frank1989/repos",
      "events_url": "https://api.github.com/users/michael-frank1989/events{/privacy}",
      "received_events_url": "https://api.github.com/users/michael-frank1989/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "frankmich-mms",
      "id": 47630109,
      "node_id": "MDQ6VXNlcjQ3NjMwMTA5",
      "avatar_url": "https://avatars3.githubusercontent.com/u/47630109?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/frankmich-mms",
      "html_url": "https://github.com/frankmich-mms",
      "followers_url": "https://api.github.com/users/frankmich-mms/followers",
      "following_url": "https://api.github.com/users/frankmich-mms/following{/other_user}",
      "gists_url": "https://api.github.com/users/frankmich-mms/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/frankmich-mms/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/frankmich-mms/subscriptions",
      "organizations_url": "https://api.github.com/users/frankmich-mms/orgs",
      "repos_url": "https://api.github.com/users/frankmich-mms/repos",
      "events_url": "https://api.github.com/users/frankmich-mms/events{/privacy}",
      "received_events_url": "https://api.github.com/users/frankmich-mms/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "frank-at-adacore",
      "id": 55284511,
      "node_id": "MDQ6VXNlcjU1Mjg0NTEx",
      "avatar_url": "https://avatars3.githubusercontent.com/u/55284511?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/frank-at-adacore",
      "html_url": "https://github.com/frank-at-adacore",
      "followers_url": "https://api.github.com/users/frank-at-adacore/followers",
      "following_url": "https://api.github.com/users/frank-at-adacore/following{/other_user}",
      "gists_url": "https://api.github.com/users/frank-at-adacore/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/frank-at-adacore/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/frank-at-adacore/subscriptions",
      "organizations_url": "https://api.github.com/users/frank-at-adacore/orgs",
      "repos_url": "https://api.github.com/users/frank-at-adacore/repos",
      "events_url": "https://api.github.com/users/frank-at-adacore/events{/privacy}",
      "received_events_url": "https://api.github.com/users/frank-at-adacore/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}''';
